import type { PopupDoc } from "./spec";

export const DEMO_PRESETS: Array<{ id: string; prompt: string; doc: PopupDoc }> = [
  {
    id: "bf",
    prompt: "Upcoming Black Friday sale with up to 50% off. Add image, headline, short body and 2 CTAs.",
    doc: {
      version: "2.0",
      container: {
        id: "container",
        name: "Container",
        mode: "light",
        aspectRatio: 0.72,
        maxWidth: 420,
        cornerRadius: 18,
        backgroundColor: "#FFFFFF",
        showCloseIcon: true,
        backdrop: true,
        dismissible: true,
        brandColor: "#2563EB",
        textColor: "#0F172A",
        mutedTextColor: "#475569",
      },
      elements: [
        {
          id: "img1",
          kind: "image",
          name: "Image 1",
          hidden: false,
          url: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80",
          alt: "Shopping bags and sale background",
          height: 220,
          fit: "cover",
          cornerRadius: 16,
        },
        {
          id: "t1",
          kind: "text",
          name: "Text 1",
          hidden: false,
          text: "Black Friday is live",
          fontFamily: "Inter, system-ui, Arial",
          fontSize: 22,
          fontWeight: 800,
          align: "center",
          color: "#0F172A",
        },
        {
          id: "t2",
          kind: "text",
          name: "Text 2",
          hidden: false,
          text: "Up to 50% off bestsellers. Limited time—while stock lasts.",
          fontFamily: "Inter, system-ui, Arial",
          fontSize: 14,
          fontWeight: 550,
          align: "center",
          color: "#475569",
        },
        {
          id: "b1",
          kind: "button",
          name: "Button 1",
          hidden: false,
          label: "Shop Now",
          fontSize: 14,
          fontWeight: 750,
          cornerRadius: 12,
          fillColor: "#2563EB",
          textColor: "#FFFFFF",
          actionType: "url",
          actionValue: "https://example.com/black-friday",
          fullWidth: true,
        },
        {
          id: "b2",
          kind: "button",
          name: "Button 2",
          hidden: false,
          label: "Maybe later",
          fontSize: 14,
          fontWeight: 700,
          cornerRadius: 12,
          fillColor: "#EEF2FF",
          textColor: "#1E3A8A",
          actionType: "dismiss",
          actionValue: "",
          fullWidth: true,
        },
      ],
    },
  },

  {
    id: "welcome",
    prompt: "Welcome popup for new users. Add quick tour CTA and no image. Minimal style.",
    doc: {
      version: "2.0",
      container: {
        id: "container",
        name: "Container",
        mode: "light",
        aspectRatio: 0.78,
        maxWidth: 420,
        cornerRadius: 18,
        backgroundColor: "#FFFFFF",
        showCloseIcon: true,
        backdrop: true,
        dismissible: true,
        brandColor: "#16A34A",
        textColor: "#0F172A",
        mutedTextColor: "#475569",
      },
      elements: [
        {
          id: "t1",
          kind: "text",
          name: "Text 1",
          hidden: false,
          text: "Welcome to CleverTap",
          fontFamily: "Inter, system-ui, Arial",
          fontSize: 22,
          fontWeight: 850,
          align: "left",
          color: "#0F172A",
        },
        {
          id: "t2",
          kind: "text",
          name: "Text 2",
          hidden: false,
          text: "Set up your first campaign in under 2 minutes. We’ll guide you through the essentials.",
          fontFamily: "Inter, system-ui, Arial",
          fontSize: 14,
          fontWeight: 550,
          align: "left",
          color: "#475569",
        },
        {
          id: "b1",
          kind: "button",
          name: "Button 1",
          hidden: false,
          label: "Start the tour",
          fontSize: 14,
          fontWeight: 750,
          cornerRadius: 12,
          fillColor: "#16A34A",
          textColor: "#FFFFFF",
          actionType: "url",
          actionValue: "https://example.com/tour",
          fullWidth: true,
        },
      ],
    },
  },

  {
    id: "leadgen",
    prompt: "Lead generation popup. Add headline, short pitch, CTA ‘Get the guide’. Dark theme.",
    doc: {
      version: "2.0",
      container: {
        id: "container",
        name: "Container",
        mode: "dark",
        aspectRatio: 0.74,
        maxWidth: 420,
        cornerRadius: 18,
        backgroundColor: "#0B1220",
        showCloseIcon: true,
        backdrop: true,
        dismissible: true,
        brandColor: "#F97316",
        textColor: "#E5E7EB",
        mutedTextColor: "#9CA3AF",
      },
      elements: [
        {
          id: "img1",
          kind: "image",
          name: "Image 1",
          hidden: false,
          url: "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1200&q=80",
          alt: "Dashboard analytics",
          height: 210,
          fit: "cover",
          cornerRadius: 16,
        },
        {
          id: "t1",
          kind: "text",
          name: "Text 1",
          hidden: false,
          text: "Free guide: Retention playbook",
          fontFamily: "Inter, system-ui, Arial",
          fontSize: 20,
          fontWeight: 850,
          align: "left",
          color: "#E5E7EB",
        },
        {
          id: "t2",
          kind: "text",
          name: "Text 2",
          hidden: false,
          text: "Learn proven workflows to lift activation and reduce churn—practical, step-by-step.",
          fontFamily: "Inter, system-ui, Arial",
          fontSize: 14,
          fontWeight: 550,
          align: "left",
          color: "#9CA3AF",
        },
        {
          id: "b1",
          kind: "button",
          name: "Button 1",
          hidden: false,
          label: "Get the guide",
          fontSize: 14,
          fontWeight: 800,
          cornerRadius: 12,
          fillColor: "#F97316",
          textColor: "#0B1220",
          actionType: "url",
          actionValue: "https://example.com/guide",
          fullWidth: true,
        },
        {
          id: "b2",
          kind: "button",
          name: "Button 2",
          hidden: false,
          label: "Not now",
          fontSize: 14,
          fontWeight: 700,
          cornerRadius: 12,
          fillColor: "rgba(255,255,255,0.10)",
          textColor: "#E5E7EB",
          actionType: "dismiss",
          actionValue: "",
          fullWidth: true,
        },
      ],
    },
  },

  {
    id: "survey",
    prompt: "Survey popup asking for rating. Add headline and CTA ‘Submit’.",
    doc: {
      version: "2.0",
      container: {
        id: "container",
        name: "Container",
        mode: "light",
        aspectRatio: 0.8,
        maxWidth: 420,
        cornerRadius: 18,
        backgroundColor: "#FFFFFF",
        showCloseIcon: true,
        backdrop: true,
        dismissible: true,
        brandColor: "#7C3AED",
        textColor: "#0F172A",
        mutedTextColor: "#475569",
      },
      elements: [
        {
          id: "t1",
          kind: "text",
          name: "Text 1",
          hidden: false,
          text: "How was your experience?",
          fontFamily: "Inter, system-ui, Arial",
          fontSize: 20,
          fontWeight: 850,
          align: "center",
          color: "#0F172A",
        },
        {
          id: "t2",
          kind: "text",
          name: "Text 2",
          hidden: false,
          text: "Tap a rating to help us improve. It takes 5 seconds.",
          fontFamily: "Inter, system-ui, Arial",
          fontSize: 14,
          fontWeight: 550,
          align: "center",
          color: "#475569",
        },
        {
          id: "t3",
          kind: "text",
          name: "Text 3",
          hidden: false,
          text: "★★★★★",
          fontFamily: "Inter, system-ui, Arial",
          fontSize: 22,
          fontWeight: 850,
          align: "center",
          color: "#7C3AED",
        },
        {
          id: "b1",
          kind: "button",
          name: "Button 1",
          hidden: false,
          label: "Submit",
          fontSize: 14,
          fontWeight: 800,
          cornerRadius: 12,
          fillColor: "#7C3AED",
          textColor: "#FFFFFF",
          actionType: "dismiss",
          actionValue: "",
          fullWidth: true,
        },
      ],
    },
  },

  {
    id: "shipping",
    prompt: "Order update: free shipping for 24 hours. Banner style. One CTA.",
    doc: {
      version: "2.0",
      container: {
        id: "container",
        name: "Container",
        mode: "light",
        aspectRatio: 2.6,
        maxWidth: 860,
        cornerRadius: 14,
        backgroundColor: "#FFFFFF",
        showCloseIcon: true,
        backdrop: false,
        dismissible: true,
        brandColor: "#0EA5E9",
        textColor: "#0F172A",
        mutedTextColor: "#475569",
      },
      elements: [
        {
          id: "t1",
          kind: "text",
          name: "Text 1",
          hidden: false,
          text: "Free shipping for 24 hours",
          fontFamily: "Inter, system-ui, Arial",
          fontSize: 18,
          fontWeight: 850,
          align: "left",
          color: "#0F172A",
        },
        {
          id: "t2",
          kind: "text",
          name: "Text 2",
          hidden: false,
          text: "Use code SHIPFAST at checkout. Ends tonight.",
          fontFamily: "Inter, system-ui, Arial",
          fontSize: 14,
          fontWeight: 550,
          align: "left",
          color: "#475569",
        },
        {
          id: "b1",
          kind: "button",
          name: "Button 1",
          hidden: false,
          label: "Apply code",
          fontSize: 14,
          fontWeight: 800,
          cornerRadius: 12,
          fillColor: "#0EA5E9",
          textColor: "#FFFFFF",
          actionType: "url",
          actionValue: "https://example.com/shipfast",
          fullWidth: false,
        },
      ],
    },
  },
];
